#!/usr/bin/env bash
# Generated by cgraf78/actions checkout-installer. Do not edit.
#
# This file is deliberately self-contained. From a real repository checkout it
# delegates immediately. When downloaded or piped to Bash, it creates or safely
# updates a durable checkout and delegates to the same repository-owned script.

{
  set -euo pipefail
  caller_umask=$(umask)
  umask 077

  checkout_repo='cgraf78/ds'
  checkout_slug='ds'
  checkout_ref='main'
  checkout_delegate='support/install-checkout.sh'
  default_repo_url="https://github.com/${checkout_repo}.git"

  die() {
    printf 'install.sh: %s\n' "$*" >&2
    exit 1
  }

  require_delegate() {
    local checkout_root=$1 delegate

    delegate="$checkout_root/$checkout_delegate"
    [[ -f "$delegate" && ! -L "$delegate" ]] ||
      die "checkout installer is missing: $delegate"
  }

  exec_bootstrap_git() {
    local config_count=${GIT_CONFIG_COUNT:-0} config_index

    if [[ "$config_count" =~ ^[0-9]+$ ]]; then
      for ((config_index = 0; config_index < config_count; config_index++)); do
        unset "GIT_CONFIG_KEY_$config_index"
        unset "GIT_CONFIG_VALUE_$config_index"
      done
    fi
    unset GIT_ALTERNATE_OBJECT_DIRECTORIES
    unset GIT_COMMON_DIR
    unset GIT_CONFIG
    unset GIT_CONFIG_COUNT
    unset GIT_CONFIG_PARAMETERS
    unset GIT_DIR
    unset GIT_GRAFT_FILE
    unset GIT_IMPLICIT_WORK_TREE
    unset GIT_INDEX_FILE
    unset GIT_INTERNAL_SUPER_PREFIX
    unset GIT_NAMESPACE
    unset GIT_NO_REPLACE_OBJECTS
    unset GIT_OBJECT_DIRECTORY
    unset GIT_PREFIX
    unset GIT_REPLACE_REF_BASE
    unset GIT_SHALLOW_FILE
    unset GIT_WORK_TREE
    GIT_TERMINAL_PROMPT=0 exec git \
      -c core.hooksPath=/dev/null \
      -c core.fsmonitor=false \
      -c submodule.recurse=false \
      -c fetch.recurseSubmodules=false \
      "$@"
  }

  bootstrap_git() {
    (exec_bootstrap_git "$@")
  }

  trusted_checkout_git() {
    local checkout_root=$1
    shift

    bootstrap_git -c "safe.directory=$checkout_root" \
      -C "$checkout_root" "$@"
  }

  network_git() {
    local status

    (
      GIT_ASKPASS=/bin/false
      SSH_ASKPASS=/bin/false
      GIT_SSH_COMMAND='ssh -oBatchMode=yes'
      export GIT_ASKPASS SSH_ASKPASS GIT_SSH_COMMAND
      exec_bootstrap_git -c credential.helper= "$@"
    ) </dev/null &
    active_child_pid=$!
    set +e
    wait "$active_child_pid"
    status=$?
    active_child_pid=
    set -e
    return "$status"
  }

  tracked_git() {
    local status

    (exec_bootstrap_git "$@") &
    active_child_pid=$!
    set +e
    wait "$active_child_pid"
    status=$?
    active_child_pid=
    set -e
    return "$status"
  }

  require_tracked_delegate() {
    local checkout_root=$1

    require_delegate "$checkout_root"
    bootstrap_git -C "$checkout_root" ls-files --error-unmatch -- \
      "$checkout_delegate" >/dev/null 2>&1 ||
      die "checkout installer is not tracked: $checkout_root/$checkout_delegate"
  }

  require_tree_delegate() {
    local checkout_root=$1 revision=$2 entry mode type object path

    entry=$(bootstrap_git -C "$checkout_root" ls-tree "$revision" -- \
      "$checkout_delegate") ||
      die "cannot inspect checkout installer in revision $revision"
    IFS=$' \t' read -r mode type object path <<<"$entry"
    [[ ("$mode" == 100644 || "$mode" == 100755) &&
      "$type" == blob && -n "$object" && "$path" == "$checkout_delegate" ]] ||
      die "checkout installer is missing from revision $revision: $checkout_delegate"
  }

  checkout_source_root() {
    local source_path=$1 script_dir top

    [[ -f "$source_path" && ! -L "$source_path" ]] || return 1
    [[ ${source_path##*/} == install.sh ]] || return 1
    script_dir=$(cd -P -- "$(dirname "$source_path")" && pwd -P) || return 1
    top=$(trusted_checkout_git "$script_dir" \
      rev-parse --show-toplevel 2>/dev/null) ||
      return 1
    top=$(cd -P -- "$top" && pwd -P) || return 1
    [[ "$top" == "$script_dir" ]] || return 1
    [[ -f "$top/install.sh" && ! -L "$top/install.sh" ]] || return 1
    [[ -f "$top/$checkout_delegate" && ! -L "$top/$checkout_delegate" ]] ||
      return 1
    trusted_checkout_git "$top" ls-files --error-unmatch -- \
      install.sh "$checkout_delegate" >/dev/null 2>&1 || return 1
    printf '%s\n' "$top"
  }

  exec_delegate() {
    local checkout_root=$1
    shift

    require_delegate "$checkout_root"
    umask "$caller_umask"
    exec /bin/bash "$checkout_root/$checkout_delegate" "$@"
  }

  # A generated installer committed at the repository root keeps ordinary
  # checkout installs fast and offline. Piped Bash has no regular source file,
  # while a downloaded standalone copy has no adjacent delegate; both continue
  # into the managed-checkout bootstrap below.
  script_source=${BASH_SOURCE[0]:-}
  if [[ -n "$script_source" ]] &&
    script_dir=$(checkout_source_root "$script_source"); then
    exec_delegate "$script_dir" "$@"
  fi

  command -v git >/dev/null 2>&1 || die 'git is required for a piped install'
  [[ -n ${HOME:-} ]] || die 'HOME is not set'

  repo_url=${CGRAF78_CHECKOUT_INSTALL_REPO_URL:-$default_repo_url}
  checkout_dir=${CGRAF78_CHECKOUT_INSTALL_DIR:-}
  if [[ -z "$checkout_dir" ]]; then
    if [[ ${XDG_DATA_HOME:-} == /* ]]; then
      data_home=$XDG_DATA_HOME
    else
      data_home=$HOME/.local/share
    fi
    checkout_dir="$data_home/cgraf78/checkouts/$checkout_slug"
  fi

  case "$checkout_dir" in
    '' | / | */ | *//* | */./* | */. | */../* | */..)
      die "managed checkout path must be a normalized absolute path: $checkout_dir"
      ;;
    /*) ;;
    *)
      die "managed checkout path must be absolute: $checkout_dir"
      ;;
  esac

  checkout_parent=${checkout_dir%/*}
  checkout_name=${checkout_dir##*/}
  [[ -n "$checkout_parent" ]] || checkout_parent=/
  mkdir -p "$checkout_parent" ||
    die "cannot create managed checkout parent: $checkout_parent"
  [[ -d "$checkout_parent" ]] ||
    die "managed checkout parent is not a directory: $checkout_parent"
  checkout_parent=$(cd -P -- "$checkout_parent" && pwd -P) ||
    die "cannot resolve managed checkout parent: $checkout_parent"
  checkout_dir="$checkout_parent/$checkout_name"

  staging=
  publish_identity=
  active_child_pid=
  lock_dir="$checkout_parent/.${checkout_slug}.install.lock"
  lock_held=0

  # shellcheck disable=SC2329 # Called by cleanup through the EXIT trap.
  release_lock() {
    if [[ "$lock_held" -eq 1 ]]; then
      rmdir "$lock_dir" 2>/dev/null || true
      lock_held=0
    fi
  }

  # shellcheck disable=SC2329 # Installed as the EXIT trap below.
  recover_staging_location() {
    local expected nested

    [[ -n "$publish_identity" && -f "$publish_identity" &&
      ! -L "$publish_identity" ]] || return 0
    expected="$checkout_dir/.git/cgraf78-publish-identity"
    nested="$checkout_dir/${staging##*/}/.git/cgraf78-publish-identity"
    if [[ -f "$expected" && "$publish_identity" -ef "$expected" ]]; then
      staging=$checkout_dir
    elif [[ -n "$staging" && -f "$nested" &&
      "$publish_identity" -ef "$nested" ]]; then
      staging=${nested%/.git/cgraf78-publish-identity}
    fi
  }

  # shellcheck disable=SC2329 # Installed as the EXIT trap below.
  cleanup() {
    local status=$?

    trap - EXIT HUP INT TERM
    recover_staging_location
    if [[ -n "$staging" && -d "$staging" && ! -L "$staging" ]]; then
      rm -rf -- "$staging"
    fi
    if [[ -n "$publish_identity" && -f "$publish_identity" &&
      ! -L "$publish_identity" ]]; then
      rm -f -- "$publish_identity"
    fi
    release_lock
    exit "$status"
  }

  # shellcheck disable=SC2329 # Reached by the signal-trap call chain below.
  signal_snapshot_children() {
    local parent=$1 signal=$2 snapshot=$3 child children live_parent

    children=$(printf '%s\n' "$snapshot" |
      command awk -v parent="$parent" '$2 == parent { print $1 }')
    for child in $children; do
      signal_snapshot_children "$child" "$signal" "$snapshot"
      live_parent=$(command ps -o ppid= -p "$child" 2>/dev/null || true)
      live_parent=${live_parent//[[:space:]]/}
      if [[ "$live_parent" == "$parent" ]]; then
        kill -s "$signal" "$child" 2>/dev/null || true
      fi
    done
  }

  # shellcheck disable=SC2329 # Reached by the signal-trap call chain below.
  signal_process_tree() {
    local root=$1 signal=$2 snapshot

    snapshot=$(command ps -eo pid=,ppid= 2>/dev/null || true)
    signal_snapshot_children "$root" "$signal" "$snapshot"
    kill -s "$signal" "$root" 2>/dev/null || true
  }

  # shellcheck disable=SC2329 # Installed as the signal traps below.
  forward_signal() {
    local signal=$1 status=$2

    trap - HUP INT TERM
    if [[ -n "$active_child_pid" ]]; then
      signal_process_tree "$active_child_pid" "$signal"
      wait "$active_child_pid" 2>/dev/null || true
      active_child_pid=
    fi
    exit "$status"
  }

  trap cleanup EXIT
  trap 'forward_signal HUP 129' HUP
  trap 'forward_signal INT 130' INT
  trap 'forward_signal TERM 143' TERM

  if ! mkdir "$lock_dir" 2>/dev/null; then
    die "another install is using the managed checkout lock: $lock_dir"
  fi
  lock_held=1

  validate_managed_checkout() {
    local candidate=$1 top branch origin status

    [[ -d "$candidate" && ! -L "$candidate" ]] ||
      die "destination is not a managed Git checkout: $candidate"
    top=$(bootstrap_git -C "$candidate" rev-parse --show-toplevel 2>/dev/null) ||
      die "destination is not a managed Git checkout: $candidate"
    top=$(cd -P -- "$top" && pwd -P) ||
      die "cannot resolve managed Git checkout: $candidate"
    candidate=$(cd -P -- "$candidate" && pwd -P) ||
      die "cannot resolve managed Git checkout: $candidate"
    [[ "$top" == "$candidate" ]] ||
      die "destination is not the root of its Git checkout: $candidate"

    origin=$(bootstrap_git -C "$candidate" remote get-url origin 2>/dev/null) ||
      die "managed Git checkout has no origin: $candidate"
    [[ "$origin" == "$repo_url" ]] ||
      die "managed Git checkout origin differs: $origin"
    branch=$(bootstrap_git -C "$candidate" symbolic-ref --quiet --short HEAD 2>/dev/null) ||
      die "managed Git checkout is detached: $candidate"
    [[ "$branch" == "$checkout_ref" ]] ||
      die "managed Git checkout branch differs: $branch"
    status=$(bootstrap_git -C "$candidate" status --porcelain \
      --untracked-files=normal) ||
      die "cannot inspect managed Git checkout: $candidate"
    [[ -z "$status" ]] ||
      die "managed Git checkout is dirty; refusing to update: $candidate"
  }

  if [[ -e "$checkout_dir" || -L "$checkout_dir" ]]; then
    validate_managed_checkout "$checkout_dir"
    printf 'install.sh: updating %s\n' "$checkout_dir"
    network_git -C "$checkout_dir" \
      fetch --quiet --no-tags origin "$checkout_ref" </dev/null ||
      die "cannot fetch $checkout_repo branch $checkout_ref"
    fetched_head=$(bootstrap_git -C "$checkout_dir" rev-parse FETCH_HEAD) ||
      die "cannot resolve fetched $checkout_repo revision"
    require_tree_delegate "$checkout_dir" "$fetched_head"
    tracked_git -C "$checkout_dir" merge --quiet --ff-only "$fetched_head" ||
      die "managed Git checkout cannot fast-forward: $checkout_dir"
    current_head=$(bootstrap_git -C "$checkout_dir" rev-parse HEAD) ||
      die "cannot resolve managed Git checkout revision: $checkout_dir"
    [[ "$current_head" == "$fetched_head" ]] ||
      die "managed Git checkout contains commits outside origin/$checkout_ref"
    validate_managed_checkout "$checkout_dir"
    require_tracked_delegate "$checkout_dir"
  else
    staging=$(mktemp -d "$checkout_parent/.${checkout_slug}.clone.XXXXXX") ||
      die "cannot create checkout staging directory under $checkout_parent"
    printf 'install.sh: cloning %s to %s\n' "$checkout_repo" "$checkout_dir"
    network_git -c init.templateDir= \
      clone --quiet --depth 1 --single-branch --branch "$checkout_ref" \
      --no-tags -- "$repo_url" "$staging" </dev/null ||
      die "cannot clone $checkout_repo branch $checkout_ref"
    validate_managed_checkout "$staging"
    require_tree_delegate "$staging" HEAD
    require_tracked_delegate "$staging"
    [[ ! -e "$checkout_dir" && ! -L "$checkout_dir" ]] ||
      die "managed checkout destination appeared during clone: $checkout_dir"
    publish_identity=$(mktemp "$checkout_parent/.${checkout_slug}.publish.XXXXXX") ||
      die "cannot create checkout publication identity under $checkout_parent"
    ln "$publish_identity" "$staging/.git/cgraf78-publish-identity" ||
      die 'cannot prepare checkout publication identity'
    mv -n "$staging" "$checkout_dir" ||
      die "cannot publish managed checkout: $checkout_dir"
    if [[ ! -f "$checkout_dir/.git/cgraf78-publish-identity" ||
      ! "$publish_identity" -ef "$checkout_dir/.git/cgraf78-publish-identity" ]]; then
      recover_staging_location
      die "managed checkout destination appeared during publication: $checkout_dir"
    fi
    rm -f -- "$checkout_dir/.git/cgraf78-publish-identity" "$publish_identity"
    publish_identity=
    staging=
    validate_managed_checkout "$checkout_dir"
    require_tracked_delegate "$checkout_dir"
  fi

  require_delegate "$checkout_dir"
  umask "$caller_umask"
  set +e
  /bin/bash "$checkout_dir/$checkout_delegate" "$@" <&0 &
  active_child_pid=$!
  wait "$active_child_pid"
  delegate_status=$?
  active_child_pid=
  set -e
  exit "$delegate_status"
}
