name: CI

on:
  push:
    branches: [master, main]
  pull_request:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell:
    uses: cgraf78/actions/.github/workflows/shell-ci.yml@ac5330ce8cc9b5a060a0e21d6ef1a5457c183fb6
    with:
      profiles: base,openssh-netcat-lsof,procps,shellcheck
      test-command: bash tests/ds-ci
